package com.example.vitalsync.utility;

public enum CoberturaMedica {

    SWISS_MEDICAL, ACTIVA_SALUD, AMFFA, AMIL, ASMEPRIV, ASOCIACION_MUTUAL_SANCOR, ASOCIART_ART, ASSPE,
    AUSTRAL_SALUD, AVALIAN, BERKLEY_ART, BRINDAR_SALUD, BRISTOL_MEDICINE, CASA, CEMIC,
    Centro_Médico_Pueyrredón, CIMU, CITYMED, COBERMED, VTE_LOPEZ, COLEGIO_ESCRIBANOS_DE_CAP_FED,
    COLEGIO_ESCRIBANOS_DE_LA_PCIA_DE_BS_AS, CONSULMED_ODONTO, DOCTORED, DOSUBA, ENSALUD, FAMILY_GROUP,
    GALENO, GALENO_ART, HTAL_ALEMAN, HTAL_BRITANICO, HTAL_ITALIANO, IOMA, IOSFA, LEAL_MEDICA,
    LUIS_PASTEUR, MEDICUS, MEDIFE, MEGADIAGNOSTICO_OMINT, OMINT, OSDE, OSDEPYM, UNION_PERSONAL, PARTICULAR
}